#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 95
#define LARGE_STATE_COUNT 6
#define SYMBOL_COUNT 31
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_COLON = 1,
  sym__space = 2,
  sym_identifier = 3,
  sym_type = 4,
  sym_number = 5,
  anon_sym_LBRACK = 6,
  anon_sym_COMMA = 7,
  anon_sym_RBRACK = 8,
  anon_sym_SQUOTE = 9,
  aux_sym_string_token1 = 10,
  anon_sym_include = 11,
  anon_sym_LBRACE = 12,
  anon_sym_RBRACE = 13,
  sym__indent = 14,
  sym_source_file = 15,
  sym_function_call = 16,
  sym_function_definition = 17,
  sym__statement = 18,
  sym__expression = 19,
  sym__node = 20,
  sym__literal = 21,
  aux_sym__block = 22,
  sym_list = 23,
  sym_string = 24,
  sym_include = 25,
  sym_data = 26,
  aux_sym_source_file_repeat1 = 27,
  aux_sym__block_repeat1 = 28,
  aux_sym_list_repeat1 = 29,
  aux_sym_data_repeat1 = 30,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COLON] = ":",
  [sym__space] = "_space",
  [sym_identifier] = "identifier",
  [sym_type] = "type",
  [sym_number] = "number",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_include] = "include",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym__indent] = "_indent",
  [sym_source_file] = "source_file",
  [sym_function_call] = "function_call",
  [sym_function_definition] = "function_definition",
  [sym__statement] = "_statement",
  [sym__expression] = "_expression",
  [sym__node] = "_node",
  [sym__literal] = "_literal",
  [aux_sym__block] = "_block",
  [sym_list] = "list",
  [sym_string] = "string",
  [sym_include] = "include",
  [sym_data] = "data",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__block_repeat1] = "_block_repeat1",
  [aux_sym_list_repeat1] = "list_repeat1",
  [aux_sym_data_repeat1] = "data_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym__space] = sym__space,
  [sym_identifier] = sym_identifier,
  [sym_type] = sym_type,
  [sym_number] = sym_number,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_include] = anon_sym_include,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym__indent] = sym__indent,
  [sym_source_file] = sym_source_file,
  [sym_function_call] = sym_function_call,
  [sym_function_definition] = sym_function_definition,
  [sym__statement] = sym__statement,
  [sym__expression] = sym__expression,
  [sym__node] = sym__node,
  [sym__literal] = sym__literal,
  [aux_sym__block] = aux_sym__block,
  [sym_list] = sym_list,
  [sym_string] = sym_string,
  [sym_include] = sym_include,
  [sym_data] = sym_data,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__block_repeat1] = aux_sym__block_repeat1,
  [aux_sym_list_repeat1] = aux_sym_list_repeat1,
  [aux_sym_data_repeat1] = aux_sym_data_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym__space] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_include] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym__indent] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__block] = {
    .visible = false,
    .named = false,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_include] = {
    .visible = true,
    .named = true,
  },
  [sym_data] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_data_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 3,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 7,
  [9] = 6,
  [10] = 10,
  [11] = 10,
  [12] = 12,
  [13] = 10,
  [14] = 7,
  [15] = 12,
  [16] = 6,
  [17] = 6,
  [18] = 10,
  [19] = 12,
  [20] = 12,
  [21] = 7,
  [22] = 22,
  [23] = 22,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 35,
  [40] = 30,
  [41] = 29,
  [42] = 42,
  [43] = 34,
  [44] = 25,
  [45] = 45,
  [46] = 38,
  [47] = 42,
  [48] = 48,
  [49] = 31,
  [50] = 37,
  [51] = 51,
  [52] = 45,
  [53] = 28,
  [54] = 51,
  [55] = 55,
  [56] = 56,
  [57] = 48,
  [58] = 56,
  [59] = 32,
  [60] = 36,
  [61] = 61,
  [62] = 26,
  [63] = 61,
  [64] = 51,
  [65] = 27,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 56,
  [71] = 56,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 69,
  [77] = 75,
  [78] = 67,
  [79] = 73,
  [80] = 68,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 82,
  [86] = 82,
  [87] = 82,
  [88] = 88,
  [89] = 88,
  [90] = 90,
  [91] = 90,
  [92] = 88,
  [93] = 88,
  [94] = 94,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      if (lookahead == '\t') ADVANCE(10);
      if (lookahead == ' ') ADVANCE(11);
      if (lookahead == '\'') ADVANCE(26);
      if (lookahead == ',') ADVANCE(24);
      if (lookahead == ':') ADVANCE(9);
      if (lookahead == '[') ADVANCE(23);
      if (lookahead == ']') ADVANCE(25);
      if (lookahead == 'i') ADVANCE(18);
      if (lookahead == '{') ADVANCE(30);
      if (lookahead == '}') ADVANCE(31);
      if (('\n' <= lookahead && lookahead <= '\r')) ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(21);
      END_STATE();
    case 1:
      if (lookahead == '\t') ADVANCE(10);
      if (lookahead == ' ') ADVANCE(11);
      if (lookahead == '\'') ADVANCE(26);
      if (lookahead == ',') ADVANCE(24);
      if (lookahead == ':') ADVANCE(9);
      if (lookahead == '[') ADVANCE(23);
      if (lookahead == '{') ADVANCE(30);
      if (lookahead == '}') ADVANCE(31);
      if (('\n' <= lookahead && lookahead <= '\r')) ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 2:
      if (lookahead == '\'') ADVANCE(26);
      if (lookahead == ',') ADVANCE(24);
      if (lookahead == ':') ADVANCE(9);
      if (lookahead == '[') ADVANCE(23);
      if (lookahead == ']') ADVANCE(25);
      if (lookahead == '{') ADVANCE(30);
      if (lookahead == '}') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(4);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(12);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(13);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == '\'') ADVANCE(27);
      END_STATE();
    case 5:
      if (lookahead == '\'') ADVANCE(28);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == '\'') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 7:
      if (eof) ADVANCE(8);
      if (lookahead == '\'') ADVANCE(26);
      if (lookahead == ',') ADVANCE(24);
      if (lookahead == ':') ADVANCE(9);
      if (lookahead == '[') ADVANCE(23);
      if (lookahead == ']') ADVANCE(25);
      if (lookahead == 'i') ADVANCE(18);
      if (lookahead == '{') ADVANCE(30);
      if (lookahead == '}') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(21);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym__space);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym__space);
      if (lookahead == ' ') ADVANCE(32);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym__space);
      if (lookahead == '\'') ADVANCE(27);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym__space);
      if (lookahead == '\'') ADVANCE(28);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(17);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(16);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(29);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(19);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(14);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(15);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_type);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\'') ADVANCE(27);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_include);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym__indent);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 7},
  [2] = {.lex_state = 7},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 7},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 7},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 7},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 7},
  [30] = {.lex_state = 7},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 7},
  [39] = {.lex_state = 7},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 7},
  [43] = {.lex_state = 7},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 7},
  [50] = {.lex_state = 7},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 7},
  [53] = {.lex_state = 7},
  [54] = {.lex_state = 7},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 7},
  [58] = {.lex_state = 7},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 2},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 2},
  [64] = {.lex_state = 1},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 2},
  [67] = {.lex_state = 7},
  [68] = {.lex_state = 7},
  [69] = {.lex_state = 2},
  [70] = {.lex_state = 7},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 7},
  [73] = {.lex_state = 7},
  [74] = {.lex_state = 7},
  [75] = {.lex_state = 7},
  [76] = {.lex_state = 2},
  [77] = {.lex_state = 7},
  [78] = {.lex_state = 7},
  [79] = {.lex_state = 7},
  [80] = {.lex_state = 7},
  [81] = {.lex_state = 2},
  [82] = {.lex_state = 7},
  [83] = {.lex_state = 7},
  [84] = {.lex_state = 7},
  [85] = {.lex_state = 7},
  [86] = {.lex_state = 7},
  [87] = {.lex_state = 7},
  [88] = {.lex_state = 7},
  [89] = {.lex_state = 7},
  [90] = {.lex_state = 3},
  [91] = {.lex_state = 3},
  [92] = {.lex_state = 7},
  [93] = {.lex_state = 7},
  [94] = {.lex_state = 7},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym__space] = ACTIONS(3),
    [sym_identifier] = ACTIONS(1),
    [sym_type] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_include] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym__indent] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(94),
    [sym_function_call] = STATE(5),
    [sym_function_definition] = STATE(5),
    [sym__statement] = STATE(5),
    [sym__expression] = STATE(5),
    [sym__node] = STATE(5),
    [sym__literal] = STATE(5),
    [sym_list] = STATE(5),
    [sym_string] = STATE(5),
    [sym_include] = STATE(5),
    [sym_data] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym__space] = ACTIONS(7),
    [sym_identifier] = ACTIONS(9),
    [sym_number] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_include] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
  },
  [2] = {
    [sym_function_call] = STATE(2),
    [sym_function_definition] = STATE(2),
    [sym__statement] = STATE(2),
    [sym__expression] = STATE(2),
    [sym__node] = STATE(2),
    [sym__literal] = STATE(2),
    [sym_list] = STATE(2),
    [sym_string] = STATE(2),
    [sym_include] = STATE(2),
    [sym_data] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(21),
    [sym__space] = ACTIONS(7),
    [sym_identifier] = ACTIONS(23),
    [sym_number] = ACTIONS(26),
    [anon_sym_LBRACK] = ACTIONS(29),
    [anon_sym_SQUOTE] = ACTIONS(32),
    [anon_sym_include] = ACTIONS(35),
    [anon_sym_LBRACE] = ACTIONS(38),
  },
  [3] = {
    [sym_function_call] = STATE(33),
    [sym_function_definition] = STATE(33),
    [sym__statement] = STATE(33),
    [sym__expression] = STATE(33),
    [sym__node] = STATE(33),
    [sym__literal] = STATE(33),
    [sym_list] = STATE(33),
    [sym_string] = STATE(33),
    [sym_include] = STATE(33),
    [sym_data] = STATE(33),
    [aux_sym__block_repeat1] = STATE(55),
    [sym__space] = ACTIONS(3),
    [sym_identifier] = ACTIONS(41),
    [sym_number] = ACTIONS(43),
    [anon_sym_LBRACK] = ACTIONS(45),
    [anon_sym_SQUOTE] = ACTIONS(47),
    [anon_sym_include] = ACTIONS(49),
    [anon_sym_LBRACE] = ACTIONS(51),
    [sym__indent] = ACTIONS(53),
  },
  [4] = {
    [sym_function_call] = STATE(33),
    [sym_function_definition] = STATE(33),
    [sym__statement] = STATE(33),
    [sym__expression] = STATE(33),
    [sym__node] = STATE(33),
    [sym__literal] = STATE(33),
    [sym_list] = STATE(33),
    [sym_string] = STATE(33),
    [sym_include] = STATE(33),
    [sym_data] = STATE(33),
    [aux_sym__block_repeat1] = STATE(55),
    [sym__space] = ACTIONS(3),
    [sym_identifier] = ACTIONS(55),
    [sym_number] = ACTIONS(43),
    [anon_sym_LBRACK] = ACTIONS(45),
    [anon_sym_SQUOTE] = ACTIONS(47),
    [anon_sym_include] = ACTIONS(49),
    [anon_sym_LBRACE] = ACTIONS(51),
    [sym__indent] = ACTIONS(53),
  },
  [5] = {
    [sym_function_call] = STATE(2),
    [sym_function_definition] = STATE(2),
    [sym__statement] = STATE(2),
    [sym__expression] = STATE(2),
    [sym__node] = STATE(2),
    [sym__literal] = STATE(2),
    [sym_list] = STATE(2),
    [sym_string] = STATE(2),
    [sym_include] = STATE(2),
    [sym_data] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(57),
    [sym__space] = ACTIONS(7),
    [sym_identifier] = ACTIONS(9),
    [sym_number] = ACTIONS(59),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_include] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(45), 1,
      anon_sym_LBRACK,
    ACTIONS(47), 1,
      anon_sym_SQUOTE,
    ACTIONS(51), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      sym_identifier,
    ACTIONS(63), 1,
      sym_number,
    ACTIONS(65), 1,
      sym__indent,
    STATE(4), 1,
      aux_sym__block_repeat1,
    STATE(26), 1,
      aux_sym__block,
    STATE(28), 6,
      sym_function_call,
      sym__expression,
      sym__literal,
      sym_list,
      sym_string,
      sym_data,
  [36] = 8,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(67), 1,
      sym_identifier,
    ACTIONS(69), 1,
      sym_number,
    ACTIONS(71), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
    STATE(25), 6,
      sym_function_call,
      sym__expression,
      sym__literal,
      sym_list,
      sym_string,
      sym_data,
  [68] = 9,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(45), 1,
      anon_sym_LBRACK,
    ACTIONS(47), 1,
      anon_sym_SQUOTE,
    ACTIONS(51), 1,
      anon_sym_LBRACE,
    ACTIONS(71), 1,
      ts_builtin_sym_end,
    ACTIONS(73), 1,
      sym_identifier,
    ACTIONS(75), 1,
      sym_number,
    ACTIONS(77), 2,
      anon_sym_include,
      sym__indent,
    STATE(44), 6,
      sym_function_call,
      sym__expression,
      sym__literal,
      sym_list,
      sym_string,
      sym_data,
  [102] = 10,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(67), 1,
      sym_identifier,
    ACTIONS(79), 1,
      sym_number,
    ACTIONS(81), 1,
      sym__indent,
    STATE(3), 1,
      aux_sym__block_repeat1,
    STATE(62), 1,
      aux_sym__block,
    STATE(53), 6,
      sym_function_call,
      sym__expression,
      sym__literal,
      sym_list,
      sym_string,
      sym_data,
  [138] = 10,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(45), 1,
      anon_sym_LBRACK,
    ACTIONS(47), 1,
      anon_sym_SQUOTE,
    ACTIONS(51), 1,
      anon_sym_LBRACE,
    ACTIONS(81), 1,
      sym__indent,
    ACTIONS(83), 1,
      sym_identifier,
    ACTIONS(85), 1,
      sym_number,
    STATE(3), 1,
      aux_sym__block_repeat1,
    STATE(65), 1,
      aux_sym__block,
    STATE(45), 6,
      sym_function_call,
      sym__expression,
      sym__literal,
      sym_list,
      sym_string,
      sym_data,
  [174] = 10,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(65), 1,
      sym__indent,
    ACTIONS(87), 1,
      sym_identifier,
    ACTIONS(89), 1,
      sym_number,
    STATE(4), 1,
      aux_sym__block_repeat1,
    STATE(27), 1,
      aux_sym__block,
    STATE(52), 6,
      sym_function_call,
      sym__expression,
      sym__literal,
      sym_list,
      sym_string,
      sym_data,
  [210] = 10,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(67), 1,
      sym_identifier,
    ACTIONS(81), 1,
      sym__indent,
    ACTIONS(91), 1,
      sym_number,
    STATE(3), 1,
      aux_sym__block_repeat1,
    STATE(60), 1,
      aux_sym__block,
    STATE(50), 6,
      sym_function_call,
      sym__expression,
      sym__literal,
      sym_list,
      sym_string,
      sym_data,
  [246] = 10,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(45), 1,
      anon_sym_LBRACK,
    ACTIONS(47), 1,
      anon_sym_SQUOTE,
    ACTIONS(51), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      sym_identifier,
    ACTIONS(65), 1,
      sym__indent,
    ACTIONS(85), 1,
      sym_number,
    STATE(4), 1,
      aux_sym__block_repeat1,
    STATE(27), 1,
      aux_sym__block,
    STATE(45), 6,
      sym_function_call,
      sym__expression,
      sym__literal,
      sym_list,
      sym_string,
      sym_data,
  [282] = 9,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(45), 1,
      anon_sym_LBRACK,
    ACTIONS(47), 1,
      anon_sym_SQUOTE,
    ACTIONS(51), 1,
      anon_sym_LBRACE,
    ACTIONS(75), 1,
      sym_number,
    ACTIONS(77), 1,
      sym__indent,
    ACTIONS(83), 1,
      sym_identifier,
    ACTIONS(71), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
    STATE(44), 6,
      sym_function_call,
      sym__expression,
      sym__literal,
      sym_list,
      sym_string,
      sym_data,
  [316] = 10,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(45), 1,
      anon_sym_LBRACK,
    ACTIONS(47), 1,
      anon_sym_SQUOTE,
    ACTIONS(51), 1,
      anon_sym_LBRACE,
    ACTIONS(81), 1,
      sym__indent,
    ACTIONS(83), 1,
      sym_identifier,
    ACTIONS(93), 1,
      sym_number,
    STATE(3), 1,
      aux_sym__block_repeat1,
    STATE(60), 1,
      aux_sym__block,
    STATE(37), 6,
      sym_function_call,
      sym__expression,
      sym__literal,
      sym_list,
      sym_string,
      sym_data,
  [352] = 10,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(45), 1,
      anon_sym_LBRACK,
    ACTIONS(47), 1,
      anon_sym_SQUOTE,
    ACTIONS(51), 1,
      anon_sym_LBRACE,
    ACTIONS(63), 1,
      sym_number,
    ACTIONS(81), 1,
      sym__indent,
    ACTIONS(83), 1,
      sym_identifier,
    STATE(3), 1,
      aux_sym__block_repeat1,
    STATE(62), 1,
      aux_sym__block,
    STATE(28), 6,
      sym_function_call,
      sym__expression,
      sym__literal,
      sym_list,
      sym_string,
      sym_data,
  [388] = 10,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(65), 1,
      sym__indent,
    ACTIONS(79), 1,
      sym_number,
    ACTIONS(87), 1,
      sym_identifier,
    STATE(4), 1,
      aux_sym__block_repeat1,
    STATE(26), 1,
      aux_sym__block,
    STATE(53), 6,
      sym_function_call,
      sym__expression,
      sym__literal,
      sym_list,
      sym_string,
      sym_data,
  [424] = 10,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(67), 1,
      sym_identifier,
    ACTIONS(81), 1,
      sym__indent,
    ACTIONS(89), 1,
      sym_number,
    STATE(3), 1,
      aux_sym__block_repeat1,
    STATE(65), 1,
      aux_sym__block,
    STATE(52), 6,
      sym_function_call,
      sym__expression,
      sym__literal,
      sym_list,
      sym_string,
      sym_data,
  [460] = 10,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(45), 1,
      anon_sym_LBRACK,
    ACTIONS(47), 1,
      anon_sym_SQUOTE,
    ACTIONS(51), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      sym_identifier,
    ACTIONS(65), 1,
      sym__indent,
    ACTIONS(93), 1,
      sym_number,
    STATE(4), 1,
      aux_sym__block_repeat1,
    STATE(36), 1,
      aux_sym__block,
    STATE(37), 6,
      sym_function_call,
      sym__expression,
      sym__literal,
      sym_list,
      sym_string,
      sym_data,
  [496] = 10,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(65), 1,
      sym__indent,
    ACTIONS(87), 1,
      sym_identifier,
    ACTIONS(91), 1,
      sym_number,
    STATE(4), 1,
      aux_sym__block_repeat1,
    STATE(36), 1,
      aux_sym__block,
    STATE(50), 6,
      sym_function_call,
      sym__expression,
      sym__literal,
      sym_list,
      sym_string,
      sym_data,
  [532] = 9,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(69), 1,
      sym_number,
    ACTIONS(71), 1,
      ts_builtin_sym_end,
    ACTIONS(77), 1,
      anon_sym_include,
    ACTIONS(95), 1,
      sym_identifier,
    STATE(25), 6,
      sym_function_call,
      sym__expression,
      sym__literal,
      sym_list,
      sym_string,
      sym_data,
  [565] = 8,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(67), 1,
      sym_identifier,
    ACTIONS(97), 1,
      sym_number,
    ACTIONS(99), 1,
      anon_sym_RBRACK,
    STATE(79), 6,
      sym_function_call,
      sym__expression,
      sym__literal,
      sym_list,
      sym_string,
      sym_data,
  [595] = 8,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(67), 1,
      sym_identifier,
    ACTIONS(101), 1,
      sym_number,
    ACTIONS(103), 1,
      anon_sym_RBRACK,
    STATE(73), 6,
      sym_function_call,
      sym__expression,
      sym__literal,
      sym_list,
      sym_string,
      sym_data,
  [625] = 7,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(67), 1,
      sym_identifier,
    ACTIONS(105), 1,
      sym_number,
    STATE(83), 6,
      sym_function_call,
      sym__expression,
      sym__literal,
      sym_list,
      sym_string,
      sym_data,
  [652] = 3,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(109), 2,
      sym_identifier,
      anon_sym_include,
    ACTIONS(107), 8,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [670] = 6,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(65), 1,
      sym__indent,
    STATE(4), 1,
      aux_sym__block_repeat1,
    STATE(32), 1,
      aux_sym__block,
    ACTIONS(113), 2,
      sym_identifier,
      anon_sym_include,
    ACTIONS(111), 5,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
  [694] = 6,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(65), 1,
      sym__indent,
    STATE(4), 1,
      aux_sym__block_repeat1,
    STATE(32), 1,
      aux_sym__block,
    ACTIONS(117), 2,
      sym_identifier,
      anon_sym_include,
    ACTIONS(115), 5,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
  [718] = 3,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(113), 3,
      sym_identifier,
      anon_sym_include,
      sym__indent,
    ACTIONS(111), 7,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [736] = 3,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(121), 2,
      sym_identifier,
      anon_sym_include,
    ACTIONS(119), 8,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [754] = 3,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(125), 2,
      sym_identifier,
      anon_sym_include,
    ACTIONS(123), 8,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [772] = 3,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(129), 3,
      sym_identifier,
      anon_sym_include,
      sym__indent,
    ACTIONS(127), 7,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [790] = 6,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(135), 1,
      sym__indent,
    STATE(4), 1,
      aux_sym__block_repeat1,
    STATE(32), 1,
      aux_sym__block,
    ACTIONS(133), 2,
      sym_identifier,
      anon_sym_include,
    ACTIONS(131), 5,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
  [814] = 3,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(133), 3,
      sym_identifier,
      anon_sym_include,
      sym__indent,
    ACTIONS(131), 7,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [832] = 3,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(140), 3,
      sym_identifier,
      anon_sym_include,
      sym__indent,
    ACTIONS(138), 7,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [850] = 3,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(144), 3,
      sym_identifier,
      anon_sym_include,
      sym__indent,
    ACTIONS(142), 7,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [868] = 6,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(65), 1,
      sym__indent,
    STATE(4), 1,
      aux_sym__block_repeat1,
    STATE(32), 1,
      aux_sym__block,
    ACTIONS(148), 2,
      sym_identifier,
      anon_sym_include,
    ACTIONS(146), 5,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
  [892] = 3,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(148), 3,
      sym_identifier,
      anon_sym_include,
      sym__indent,
    ACTIONS(146), 7,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [910] = 3,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(152), 2,
      sym_identifier,
      anon_sym_include,
    ACTIONS(150), 8,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [928] = 3,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(144), 2,
      sym_identifier,
      anon_sym_include,
    ACTIONS(142), 8,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [946] = 3,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(125), 3,
      sym_identifier,
      anon_sym_include,
      sym__indent,
    ACTIONS(123), 7,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [964] = 3,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(121), 3,
      sym_identifier,
      anon_sym_include,
      sym__indent,
    ACTIONS(119), 7,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [982] = 3,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(156), 2,
      sym_identifier,
      anon_sym_include,
    ACTIONS(154), 8,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1000] = 3,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(140), 2,
      sym_identifier,
      anon_sym_include,
    ACTIONS(138), 8,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1018] = 3,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(109), 3,
      sym_identifier,
      anon_sym_include,
      sym__indent,
    ACTIONS(107), 7,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1036] = 3,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(117), 3,
      sym_identifier,
      anon_sym_include,
      sym__indent,
    ACTIONS(115), 7,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1054] = 3,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(152), 3,
      sym_identifier,
      anon_sym_include,
      sym__indent,
    ACTIONS(150), 7,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1072] = 3,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(156), 3,
      sym_identifier,
      anon_sym_include,
      sym__indent,
    ACTIONS(154), 7,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1090] = 3,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(160), 3,
      sym_identifier,
      anon_sym_include,
      sym__indent,
    ACTIONS(158), 7,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1108] = 3,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(129), 2,
      sym_identifier,
      anon_sym_include,
    ACTIONS(127), 8,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1126] = 3,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(148), 2,
      sym_identifier,
      anon_sym_include,
    ACTIONS(146), 7,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1143] = 5,
    ACTIONS(164), 1,
      anon_sym_COLON,
    ACTIONS(166), 1,
      sym__space,
    ACTIONS(168), 1,
      sym_identifier,
    ACTIONS(170), 2,
      anon_sym_include,
      sym__indent,
    ACTIONS(162), 5,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
  [1164] = 3,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(117), 2,
      sym_identifier,
      anon_sym_include,
    ACTIONS(115), 7,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1181] = 3,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(113), 2,
      sym_identifier,
      anon_sym_include,
    ACTIONS(111), 7,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1198] = 5,
    ACTIONS(170), 1,
      anon_sym_include,
    ACTIONS(172), 1,
      anon_sym_COLON,
    ACTIONS(174), 1,
      sym__space,
    ACTIONS(176), 1,
      sym_identifier,
    ACTIONS(162), 5,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
  [1218] = 5,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(182), 1,
      sym__indent,
    STATE(55), 1,
      aux_sym__block_repeat1,
    ACTIONS(178), 2,
      sym_identifier,
      anon_sym_include,
    ACTIONS(180), 4,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
  [1238] = 3,
    ACTIONS(166), 1,
      sym__space,
    ACTIONS(170), 3,
      sym_identifier,
      anon_sym_include,
      sym__indent,
    ACTIONS(162), 5,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
  [1254] = 3,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(160), 2,
      sym_identifier,
      anon_sym_include,
    ACTIONS(158), 5,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
  [1269] = 3,
    ACTIONS(174), 1,
      sym__space,
    ACTIONS(170), 2,
      sym_identifier,
      anon_sym_include,
    ACTIONS(162), 5,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
  [1284] = 5,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(185), 1,
      sym__indent,
    STATE(3), 1,
      aux_sym__block_repeat1,
    STATE(59), 1,
      aux_sym__block,
    ACTIONS(131), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1301] = 5,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(81), 1,
      sym__indent,
    STATE(3), 1,
      aux_sym__block_repeat1,
    STATE(59), 1,
      aux_sym__block,
    ACTIONS(146), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1318] = 6,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(188), 1,
      anon_sym_COLON,
    ACTIONS(190), 1,
      sym_identifier,
    ACTIONS(192), 1,
      anon_sym_COMMA,
    ACTIONS(194), 1,
      anon_sym_RBRACE,
    STATE(75), 1,
      aux_sym_data_repeat1,
  [1337] = 5,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(81), 1,
      sym__indent,
    STATE(3), 1,
      aux_sym__block_repeat1,
    STATE(59), 1,
      aux_sym__block,
    ACTIONS(111), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1354] = 6,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(188), 1,
      anon_sym_COLON,
    ACTIONS(190), 1,
      sym_identifier,
    ACTIONS(192), 1,
      anon_sym_COMMA,
    ACTIONS(196), 1,
      anon_sym_RBRACE,
    STATE(77), 1,
      aux_sym_data_repeat1,
  [1373] = 5,
    ACTIONS(170), 1,
      sym__indent,
    ACTIONS(198), 1,
      anon_sym_COLON,
    ACTIONS(200), 1,
      sym__space,
    ACTIONS(202), 1,
      sym_identifier,
    ACTIONS(162), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1390] = 5,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(81), 1,
      sym__indent,
    STATE(3), 1,
      aux_sym__block_repeat1,
    STATE(59), 1,
      aux_sym__block,
    ACTIONS(115), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1407] = 4,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(188), 1,
      anon_sym_COLON,
    ACTIONS(190), 1,
      sym_identifier,
    ACTIONS(204), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1421] = 4,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(206), 1,
      anon_sym_COMMA,
    ACTIONS(208), 1,
      anon_sym_RBRACK,
    STATE(74), 1,
      aux_sym_list_repeat1,
  [1434] = 4,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(192), 1,
      anon_sym_COMMA,
    ACTIONS(194), 1,
      anon_sym_RBRACE,
    STATE(75), 1,
      aux_sym_data_repeat1,
  [1447] = 4,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(210), 1,
      sym_identifier,
    ACTIONS(212), 1,
      anon_sym_RBRACE,
    STATE(68), 1,
      sym_function_definition,
  [1460] = 2,
    ACTIONS(214), 1,
      sym__space,
    ACTIONS(162), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1469] = 3,
    ACTIONS(170), 1,
      sym__indent,
    ACTIONS(200), 1,
      sym__space,
    ACTIONS(162), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1480] = 4,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(204), 1,
      anon_sym_RBRACE,
    ACTIONS(216), 1,
      anon_sym_COMMA,
    STATE(72), 1,
      aux_sym_data_repeat1,
  [1493] = 4,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(206), 1,
      anon_sym_COMMA,
    ACTIONS(219), 1,
      anon_sym_RBRACK,
    STATE(67), 1,
      aux_sym_list_repeat1,
  [1506] = 4,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(221), 1,
      anon_sym_COMMA,
    ACTIONS(224), 1,
      anon_sym_RBRACK,
    STATE(74), 1,
      aux_sym_list_repeat1,
  [1519] = 4,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(192), 1,
      anon_sym_COMMA,
    ACTIONS(226), 1,
      anon_sym_RBRACE,
    STATE(72), 1,
      aux_sym_data_repeat1,
  [1532] = 4,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(228), 1,
      sym_identifier,
    ACTIONS(230), 1,
      anon_sym_RBRACE,
    STATE(80), 1,
      sym_function_definition,
  [1545] = 4,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(192), 1,
      anon_sym_COMMA,
    ACTIONS(232), 1,
      anon_sym_RBRACE,
    STATE(72), 1,
      aux_sym_data_repeat1,
  [1558] = 4,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(206), 1,
      anon_sym_COMMA,
    ACTIONS(234), 1,
      anon_sym_RBRACK,
    STATE(74), 1,
      aux_sym_list_repeat1,
  [1571] = 4,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(206), 1,
      anon_sym_COMMA,
    ACTIONS(236), 1,
      anon_sym_RBRACK,
    STATE(78), 1,
      aux_sym_list_repeat1,
  [1584] = 4,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(192), 1,
      anon_sym_COMMA,
    ACTIONS(196), 1,
      anon_sym_RBRACE,
    STATE(77), 1,
      aux_sym_data_repeat1,
  [1597] = 3,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(238), 1,
      sym_identifier,
    STATE(84), 1,
      sym_function_definition,
  [1607] = 3,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(240), 1,
      anon_sym_COLON,
    ACTIONS(242), 1,
      sym_type,
  [1617] = 2,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(224), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1625] = 2,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(204), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1633] = 3,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(244), 1,
      anon_sym_COLON,
    ACTIONS(246), 1,
      sym_type,
  [1643] = 3,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(248), 1,
      anon_sym_COLON,
    ACTIONS(250), 1,
      sym_type,
  [1653] = 3,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(252), 1,
      anon_sym_COLON,
    ACTIONS(254), 1,
      sym_type,
  [1663] = 2,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(256), 1,
      anon_sym_COLON,
  [1670] = 2,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(258), 1,
      anon_sym_COLON,
  [1677] = 2,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(260), 1,
      aux_sym_string_token1,
  [1684] = 2,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(262), 1,
      aux_sym_string_token1,
  [1691] = 2,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(264), 1,
      anon_sym_COLON,
  [1698] = 2,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(266), 1,
      anon_sym_COLON,
  [1705] = 2,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(268), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(6)] = 0,
  [SMALL_STATE(7)] = 36,
  [SMALL_STATE(8)] = 68,
  [SMALL_STATE(9)] = 102,
  [SMALL_STATE(10)] = 138,
  [SMALL_STATE(11)] = 174,
  [SMALL_STATE(12)] = 210,
  [SMALL_STATE(13)] = 246,
  [SMALL_STATE(14)] = 282,
  [SMALL_STATE(15)] = 316,
  [SMALL_STATE(16)] = 352,
  [SMALL_STATE(17)] = 388,
  [SMALL_STATE(18)] = 424,
  [SMALL_STATE(19)] = 460,
  [SMALL_STATE(20)] = 496,
  [SMALL_STATE(21)] = 532,
  [SMALL_STATE(22)] = 565,
  [SMALL_STATE(23)] = 595,
  [SMALL_STATE(24)] = 625,
  [SMALL_STATE(25)] = 652,
  [SMALL_STATE(26)] = 670,
  [SMALL_STATE(27)] = 694,
  [SMALL_STATE(28)] = 718,
  [SMALL_STATE(29)] = 736,
  [SMALL_STATE(30)] = 754,
  [SMALL_STATE(31)] = 772,
  [SMALL_STATE(32)] = 790,
  [SMALL_STATE(33)] = 814,
  [SMALL_STATE(34)] = 832,
  [SMALL_STATE(35)] = 850,
  [SMALL_STATE(36)] = 868,
  [SMALL_STATE(37)] = 892,
  [SMALL_STATE(38)] = 910,
  [SMALL_STATE(39)] = 928,
  [SMALL_STATE(40)] = 946,
  [SMALL_STATE(41)] = 964,
  [SMALL_STATE(42)] = 982,
  [SMALL_STATE(43)] = 1000,
  [SMALL_STATE(44)] = 1018,
  [SMALL_STATE(45)] = 1036,
  [SMALL_STATE(46)] = 1054,
  [SMALL_STATE(47)] = 1072,
  [SMALL_STATE(48)] = 1090,
  [SMALL_STATE(49)] = 1108,
  [SMALL_STATE(50)] = 1126,
  [SMALL_STATE(51)] = 1143,
  [SMALL_STATE(52)] = 1164,
  [SMALL_STATE(53)] = 1181,
  [SMALL_STATE(54)] = 1198,
  [SMALL_STATE(55)] = 1218,
  [SMALL_STATE(56)] = 1238,
  [SMALL_STATE(57)] = 1254,
  [SMALL_STATE(58)] = 1269,
  [SMALL_STATE(59)] = 1284,
  [SMALL_STATE(60)] = 1301,
  [SMALL_STATE(61)] = 1318,
  [SMALL_STATE(62)] = 1337,
  [SMALL_STATE(63)] = 1354,
  [SMALL_STATE(64)] = 1373,
  [SMALL_STATE(65)] = 1390,
  [SMALL_STATE(66)] = 1407,
  [SMALL_STATE(67)] = 1421,
  [SMALL_STATE(68)] = 1434,
  [SMALL_STATE(69)] = 1447,
  [SMALL_STATE(70)] = 1460,
  [SMALL_STATE(71)] = 1469,
  [SMALL_STATE(72)] = 1480,
  [SMALL_STATE(73)] = 1493,
  [SMALL_STATE(74)] = 1506,
  [SMALL_STATE(75)] = 1519,
  [SMALL_STATE(76)] = 1532,
  [SMALL_STATE(77)] = 1545,
  [SMALL_STATE(78)] = 1558,
  [SMALL_STATE(79)] = 1571,
  [SMALL_STATE(80)] = 1584,
  [SMALL_STATE(81)] = 1597,
  [SMALL_STATE(82)] = 1607,
  [SMALL_STATE(83)] = 1617,
  [SMALL_STATE(84)] = 1625,
  [SMALL_STATE(85)] = 1633,
  [SMALL_STATE(86)] = 1643,
  [SMALL_STATE(87)] = 1653,
  [SMALL_STATE(88)] = 1663,
  [SMALL_STATE(89)] = 1670,
  [SMALL_STATE(90)] = 1677,
  [SMALL_STATE(91)] = 1684,
  [SMALL_STATE(92)] = 1691,
  [SMALL_STATE(93)] = 1698,
  [SMALL_STATE(94)] = 1705,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(54),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(2),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(23),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(91),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(57),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(69),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 2),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 2),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 3),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 5),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 5),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 3),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 3),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data, 3),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_data, 3),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__block, 2),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__block, 2),
  [135] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__block, 2), SHIFT_REPEAT(4),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data, 4),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_data, 4),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 4),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 4),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 4),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data, 2),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_data, 2),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include, 1),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_include, 1),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 1),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [168] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 1),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [176] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__block_repeat1, 2),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__block_repeat1, 2),
  [182] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__block_repeat1, 2), SHIFT_REPEAT(55),
  [185] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__block, 2), SHIFT_REPEAT(3),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [200] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_data_repeat1, 2),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [216] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_data_repeat1, 2), SHIFT_REPEAT(81),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [221] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2), SHIFT_REPEAT(24),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [268] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_gin(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
